const cat_Arr = ['Vegetables', 'Fruits', 'Dairy'];
const vag_image = require('../assets/images/veg.jpg');
const fruit_image = require('../assets/images/fruit.jpg');
const dairy_image = require('../assets/images/dairy.jpg');
const info = `Aliquam lorem ante, dapibus in, viverra quis, 
feugiat a, tellus. Phasellus viverra nulla ut metus
varius laoreet. Quisque rutrum. Aenean 
imperdiet. Etiam ultricies nisi vel augue. 
Curabitur ullamcorper ultricies nisi. Nam 
eget dui. `;
var veg_list = [
  {
    name: 'Sweet potatoes',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: vag_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
  {
    name: 'Broccoli',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: vag_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
  {
    name: 'Beets',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: vag_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
  {
    name: 'Carrots',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: vag_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
  {
    name: 'tomatoes',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: vag_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
  {
    name: 'onions',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: vag_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
];

var fruit_list = [
  {
    name: 'Apple',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: fruit_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
  {
    name: 'Banana',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: fruit_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
  {
    name: 'Mango',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: fruit_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
  {
    name: 'Orange',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: fruit_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
  {
    name: 'Grapes',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: fruit_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
  {
    name: 'Pineapple',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: fruit_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
];
var dairy_list = [
  {
    name: 'Butter',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: dairy_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
  {
    name: 'Cheese',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: dairy_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
  {
    name: 'Cultured Dairy',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: dairy_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
  {
    name: 'Frozen Desserts',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: dairy_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
  {
    name: 'Milk',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: dairy_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
  {
    name: 'yogurt',
    price: '$2.5',
    total: 0,
    isAddedToCart: false,
    wishlist: false,
    image: dairy_image,
    perKg: '($10.29/KG)',
    shopName: 'Harris Farm Markets',
    status: 'In stock',
  },
];
export const global = {
  cat_Arr: cat_Arr,
  veg_list: veg_list,
  fruit_list: fruit_list,
  dairy_list: dairy_list,
  info: info,
};
